

export enum MutationTypes {
    //                      AUTH_REDUCER
    SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS',
    SET_CURRENT_BOT      = 'SET_CURRENT_BOT',
    SET_USER_INITIAL_CREDENTIALS = 'SET_USER_INITIAL_CREDENTIALS',

    //                      APP
    INITIALIZE = 'INITIALIZE',
    SET_EJECT_AXIOS = 'SET_EJECT_AXIOS'
}